---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull
  namespace: default
  labels:
    app: pull

spec:
  selector:
    matchLabels:
      app: pull
  template:
    metadata:
      labels:
        app: pull
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
        - name: pull
          image: registry.gitlab.thinksnow.ru/th1nksnow/figalizer/pull:latest
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: history-env
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: history-env
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: history-env
                key: DB_NAME
          - name: DB_LOGIN
            valueFrom:
              secretKeyRef:
                name: db-user
                key: db-username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: db-password
          ports:
            - containerPort: 80

...