---

apiVersion: v1
kind: Service
metadata:
  name: pull
  namespace: default

spec:
  selector:
    app: pull
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 8010
      targetPort: 8010

...