stages:
  - build
  - deploy

build:
  only:
    - develop
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd frontend 
  script:
    - docker build -t $CI_REGISTRY_IMAGE/front:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/front:latest .
    - docker push $CI_REGISTRY_IMAGE/front:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/front:latest
    - docker rmi $CI_REGISTRY_IMAGE/front:$CI_COMMIT_SHORT_SHA
    - docker rmi $CI_REGISTRY_IMAGE/front:latest
  tags:
    - shell

deploy:
  only:
    - develop
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd docker-compose
  script:
    - docker compose down
    - docker compose pull
    - docker compose up -d
    - docker rmi $(docker images -f "dangling=true" -q)
  tags:
    - shell