---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: figalize
  namespace: default
  labels:
    app: figalize

spec:
  selector:
    matchLabels:
      app: figalize
  template:
    metadata:
      labels:
        app: figalize
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
        - name: figalize
          image: registry.gitlab.thinksnow.ru/th1nksnow/figalizer/figalize:latest
          env:
          - name: HISTORY_APPEND_URL
            valueFrom:
              configMapKeyRef:
                name: figalize-env
                key: HISTORY_APPEND_URL
          - name: FIGALIZE_API_PORT
            valueFrom:
              configMapKeyRef:
                name: figalize-env
                key: FIGALIZE_API_PORT
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config-volume
            mountPath: /var/config/
      volumes:
        - name: config-volume
          configMap:
            name: figalize-files
        
...