version: '3'

name: figa

services:
  postgresql:
    image: postgres:13
    expose:
      - '5432'
    environment:
      POSTGRES_DB: history
      POSTGRES_USER: history
      POSTGRES_PASSWORD: 123456Qq
    networks:
      figachechnaya:

  history:
    build: ../microservices/history/
    expose:
      - '8001'
    environment:
      DB_HOST: 'postgresql'
      DB_PORT: '5432'
      DB_NAME: history
      DB_LOGIN: history
      DB_PASS: 123456Qq
    networks:
      figachechnaya:
    depends_on:
      - postgresql
  
  pull:
    build: ../microservices/pull/
    expose:
      - '8010'
    environment:
      DB_HOST: 'postgresql'
      DB_PORT: '5432'
      DB_NAME: history
      DB_LOGIN: history
      DB_PASS: 123456Qq
    networks:
      figachechnaya:
    depends_on:
      - postgresql

  figalize:
    build: ../microservices/figalize/
    expose:
      - '8002'
    environment:
      HISTORY_APPEND_URL: http://history/api/append/
      FIGALIZE_API_PORT: '8002'
    networks:
      figachechnaya:
    configs:
      - source: figalize_schemes
        target: /var/config/example.json
    depends_on:
      history:
        condition: service_started

  frontend:
    build: ../frontend/
    expose:
      - '80'
    configs:
      - source: front_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      figachechnaya:
    depends_on:
      - figalize
      - history

  ingress:
    build: ./ingress/
    ports:
      - 80:80
    expose:
      - '80'
    configs:
      - source: ingress_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      figachechnaya:
        aliases:
          - "web.thinksnow.online"
    restart: always
    depends_on:
      - frontend
      - figalize
      - history

configs:
  front_conf:
    file: ./frontend/front.conf
  ingress_conf:
    file: ./ingress/ingress.conf
  figalize_schemes:
    file: ./figalize/example.json
networks:
  figachechnaya:
