---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend

spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
        - name: frontend
          image: registry.gitlab.thinksnow.ru/th1nksnow/figalizer/front:kube
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config-volume
          configMap:
            name: front

...