---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: default

spec:
  selector:
    app: front
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

...